[[test]]
input  = "rgb ( 255, 0, 0 )\n"
output = "Zadejte barvu v RGB formatu:\n#FF0000\n"

[[test]]
input  = "rgb ( 0, 255, 0 )\n"
output = "Zadejte barvu v RGB formatu:\n#00FF00\n"

[[test]]
input  = "rgb ( 0, 0, 255 )\n"
output = "Zadejte barvu v RGB formatu:\n#0000FF\n"

[[test]]
input  = "rgb ( 127, 127, 0 )\n"
output = "Zadejte barvu v RGB formatu:\n#7F7F00\n"

[[test]]
input  = "hsl ( 0, 127, 0 )\n"
output = "Zadejte barvu v RGB formatu:\nNespravny vstup.\n"

[[test]]
input  = "rgb ( 255, 0 )\n"
output = "Zadejte barvu v RGB formatu:\nNespravny vstup.\n"

[[test]]
input  = "rgb ( 1000, 127, 0 )\n"
output = "Zadejte barvu v RGB formatu:\nNespravny vstup.\n"

[[test]]
input  = "RGB ( 100, 200, 0 )\n"
output = "Zadejte barvu v RGB formatu:\nNespravny vstup.\n"

[[test]]
input  = "rgb(1,2,3)\n"
output = "Zadejte barvu v RGB formatu:\n#010203\n"

[[test]]
input  = "rgb(1, 2, 3)"
output = "Zadejte barvu v RGB formatu:\n#010203\n"

[[test]]
input  = "rgb(1, 2, 3"
output = "Zadejte barvu v RGB formatu:\nNespravny vstup.\n"
