[[test]]
input  = "0\n"
output = "ml' nob:\nQapla'\nnoH QapmeH wo' Qaw'lu'chugh yay chavbe'lu' 'ej wo' choqmeH may' DoHlu'chugh lujbe'lu'.\n"

[[test]]
input  = "1\n"
output = "ml' nob:\nQapla'\nbortaS bIr jablu'DI' reH QaQqu' nay'.\n"

[[test]]
input  = "2\n"
output = "ml' nob:\nQapla'\nQu' buSHa'chugh SuvwI', batlhHa' vangchugh, qoj matlhHa'chugh, pagh ghaH SuvwI''e'.\n"

[[test]]
input  = "3\n"
output = "ml' nob:\nQapla'\nbISeH'eghlaH'be'chugh latlh Dara'laH'be'.\n"

[[test]]
input  = "4\n"
output = "ml' nob:\nQapla'\nqaStaHvIS wa' ram loS SaD Hugh SIjlaH qetbogh loD.\n"

[[test]]
input  = "5\n"
output = "ml' nob:\nQapla'\nSuvlu'taHvIS yapbe' HoS neH.\n"

[[test]]
input  = "6\n"
output = "ml' nob:\nQapla'\nHa'DIbaH DaSop 'e' DaHechbe'chugh yIHoHQo'.\n"

[[test]]
input  = "007\n"
output = "ml' nob:\nQapla'\nHeghlu'meH QaQ jajvam.\n"

[[test]]
input  = "           8\n"
output = "ml' nob:\nQapla'\nleghlaHchu'be'chugh mIn lo'laHbe' taj jej.\n"

[[test]]
input  = "29\n"
output = "ml' nob:\nQih mi' 29\n"

[[test]]
input  = "-5\n"
output = "ml' nob:\nQih mi' -5\n"

[[test]]
input  = "abc\n"
output = "ml' nob:\nNeh mi'\n"

[[test]]
input  = "1.23\n"
output = "ml' nob:\nbIjatlh 'e' yImev\n"

[[test]]
input  = " "
output = "ml' nob:\nNeh mi'\n"

[[test]]
input  = "1"
output = "ml' nob:\nQapla'\nbortaS bIr jablu'DI' reH QaQqu' nay'.\n"

[[test]]
input  = "\n"
output = "ml' nob:\nNeh mi'\n"

[[test]]
input  = ""
output = "ml' nob:\nNeh mi'\n"

[[test]]
input  = "1\n2\n"
output = "ml' nob:\nbIjatlh 'e' yImev\n"

[[test]]
input  = "1    \n"
output = "ml' nob:\nQapla'\nbortaS bIr jablu'DI' reH QaQqu' nay'.\n"

[[test]]
input  = "1    2\n"
output = "ml' nob:\nbIjatlh 'e' yImev\n"

[[test]]
input  = "4YHI\n"
output = "ml' nob:\nbIjatlh 'e' yImev\n"

[[test]]
input  = "3Z\n"
output = "ml' nob:\nbIjatlh 'e' yImev\n"

[[test]]
input  = "1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
output = "ml' nob:\nbIjatlh 'e' yImev\n"

[[test]]
input  = "01"
output = "ml' nob:\nQapla'\nbortaS bIr jablu'DI' reH QaQqu' nay'.\n"

[[test]]
input  = "-01"
output = "ml' nob:\nQih mi' -1\n"

[[test]]
input  = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001"
output = "ml' nob:\nQapla'\nbortaS bIr jablu'DI' reH QaQqu' nay'.\n"
