[[test]]
input  = "{ [ 2 - 6, 3, 7 ] , [4-9,2,10],[ 15-30, 4, 12 ], [12-12,1,1] }\n0 6\n2 6\n1 16\n3 25\n3 26\n5 81\n5 82\n2 7\n30 2"
output = "Moznosti dopravy:\nNaklad:\nKonec: 3, cena: 14\nKonec: 3, cena: 14\nKonec: 5, cena: 48\nKonec: 12, cena: 89\nKonec: 15, cena: 101\nKonec: 30, cena: 257\nPrilis velky naklad, nelze odvezt.\nKonec: 4, cena: 31\nKonec: 30, cena: 12\n"

[[test]]
input  = "{\n  [ 17-74, 5, 44],\n  [ 57-78, 35, 19],\n  [ 39-77, 43, 29],\n  [ 56-95, 44, 9],\n  [ 8-94, 2, 8],\n  [ 52-87, 22, 14],\n  [ 31-77, 6, 39],\n  [ 64-92, 26, 35],\n  [ 43-60, 29, 32],\n  [ 46-63, 7, 49]\n}\n14 10\n32 21\n35 9\n10 21\n"
output = "Moznosti dopravy:\nNaklad:\nKonec: 17, cena: 76\nKonec: 33, cena: 182\nKonec: 35, cena: 91\nKonec: 17, cena: 108\n"

[[test]]
input  = "{ [ 10-9, 1, 1 ] }\n"
output = "Moznosti dopravy:\nNespravny vstup.\n"

[[test]]
input  = "{ [ 1-5, 1, 1 ] }\n-1 10\n"
output = "Moznosti dopravy:\nNaklad:\nNespravny vstup.\n"
